import re

players = """ 'SC Ganguly' 'BB McCullum' 'RT Ponting' 'DJ Hussey' 'Mohammad Hafeez'
 'R Dravid' 'W Jaffer' 'V Kohli' 'JH Kallis' 'CL White' 'MV Boucher'
 'B Akhil' 'AA Noffke' 'P Kumar' 'Z Khan' 'SB Joshi' 'PA Patel'
 'ML Hayden' 'MEK Hussey' 'MS Dhoni' 'SK Raina' 'JDP Oram' 'S Badrinath'
 'K Goel' 'JR Hopes' 'KC Sangakkara' 'Yuvraj Singh' 'SM Katich'
 'IK Pathan' 'T Kohli' 'YK Pathan' 'SR Watson' 'M Kaif' 'DS Lehmann'
 'RA Jadeja' 'M Rawat' 'D Salunkhe' 'SK Warne' 'SK Trivedi' 'G Gambhir'
 'V Sehwag' 'S Dhawan' 'L Ronchi' 'ST Jayasuriya' 'DJ Thornely'
 'RV Uthappa' 'PR Shah' 'AM Nayar' 'SM Pollock' 'Harbhajan Singh'
 'S Chanderpaul' 'LRPL Taylor' 'AC Gilchrist' 'Y Venugopal Rao'
 'VVS Laxman' 'A Symonds' 'RG Sharma' 'SB Styris' 'AS Yadav' 'SB Bangar'
 'WPUJC Vaas' 'RP Singh' 'WP Saha' 'LR Shukla' 'DPMD Jayawardene'
 'S Sohal' 'B Lee' 'PP Chawla' 'WA Mota' 'Kamran Akmal' 'Shahid Afridi'
 'DJ Bravo' 'MA Khote' 'A Nehra' 'GC Smith' 'Pankaj Singh' 'RR Sarwan'
 'S Sreesanth' 'VRV Singh' 'SS Tiwary' 'DS Kulkarni' 'R Vinay Kumar'
 'AB Agarkar' 'M Kartik' 'I Sharma' 'AM Rahane' 'Shoaib Malik' 'MK Tiwary'
 'KD Karthik' 'R Bhatia' 'MF Maharoof' 'VY Mahesh' 'TM Srivastava'
 'B Chipli' 'DW Steyn' 'DB Das' 'MK Pandey' 'HH Gibbs' 'DNT Zoysa'
 'D Kalyankrishna' 'SE Marsh' 'SA Asnodkar' 'Sohail Tanvir' 'Salman Butt'
 'BJ Hodge' 'Umar Gul' 'AB Dinda' 'SP Fleming' 'S Vidyut' 'JA Morkel'
 'AB de Villiers' 'LPC Silva' 'DB Ravi Teja' 'Misbah-ul-Haq' 'YV Takawale'
 'RR Raje' 'PJ Sangwan' 'Mohammad Asif' 'GD McGrath' 'Joginder Sharma'
 'MS Gony' 'M Muralitharan' 'M Ntini' 'DT Patil' 'A Kumble' 'S Anirudha'
 'MM Patel' 'CK Kapugedera' 'A Chopra' 'T Taibu' 'J Arunkumar' 'PP Ojha'
 'SP Goswami' 'SR Tendulkar' 'U Kaul' 'TM Dilshan' 'A Mishra'
 'AD Mascarenhas' 'NK Patel' 'LA Pomersbach' 'Iqbal Abdulla' 'Younis Khan'
 'PM Sarvesh Kumar' 'DP Vijaykumar' 'Shoaib Akhtar' 'Abdur Razzak' 'H Das'
 'DR Smith' 'SD Chitnis' 'CRD Fernando' 'VS Yeligati' 'L Balaji'
 'A Mukund' 'RR Powar' 'JP Duminy' 'A Flintoff' 'T Thushara' 'JD Ryder'
 'KP Pietersen' 'T Henderson' 'Kamran Khan' 'RS Bopara' 'CH Gayle'
 'MC Henriques' 'R Bishnoi' 'FH Edwards' 'KV Sharma' 'PC Valthaty'
 'RJ Quiney' 'AS Raut' 'Yashpal Singh' 'M Manhas' 'AA Bilakhia' 'AN Ghosh'
 'BAW Mendis' 'DL Vettori' 'MN van Wyk' 'RE van der Merwe' 'TL Suman'
 'Shoaib Ahmed' 'GR Napier' 'KP Appanna' 'LA Carseldine' 'NV Ojha'
 'SM Harwood' 'M Vijay' 'SB Jakati' 'DA Warner' 'RJ Harris' 'D du Preez'
 'M Morkel' 'AD Mathews' 'J Botha' 'C Nanda' 'SL Malinga'
 'Mashrafe Mortaza' 'A Singh' 'GJ Bailey' 'AB McDonald' 'Y Nagar'
 'SS Shaikh' 'R Ashwin' 'Mohammad Ashraful' 'CA Pujara' 'OA Shah'
 'Anirudh Singh' 'Jaskaran Singh' 'AP Tare' 'AT Rayudu' 'R Sathish'
 'R McLaren' 'AA Jhunjhunwala' 'P Dogra' 'A Uniyal' 'MS Bisla'
 'YA Abdulla' 'EJG Morgan' 'JM Kemp' 'S Tyagi' 'RS Gavaskar' 'SE Bond'
 'KA Pollard' 'S Ladda' 'DP Nannes' 'MJ Lumb' 'DR Martyn' 'S Narwal'
 'AB Barath' 'Bipul Sharma' 'FY Fazal' 'AC Voges' 'MD Mishra' 'UT Yadav'
 'J Theron' 'SJ Srivastava' 'R Sharma' 'Mandeep Singh' 'KM Jadhav'
 'SW Tait' 'KB Arun Karthik' 'KAJ Roach' 'PD Collingwood' 'CK Langeveldt'
 'VS Malik' 'A Mithun' 'AP Dole' 'AN Ahmed' 'RS Sodhi' 'DE Bollinger'
 'S Sriram' 'B Sumanth' 'C Madan' 'AG Paunikar' 'MR Marsh' 'AJ Finch'
 'STR Binny' 'Harmeet Singh' 'IR Jaggi' 'DT Christian' 'UBT Chand'
 'DJ Jacobs' 'AL Menaria' 'MA Agarwal' 'AUK Pathan' 'Sunny Singh'
 'JJ van der Wath' 'R Ninan' 'S Aravind' 'DH Yagnik' 'S Randiv'
 'BJ Haddin' 'MS Wade' 'J Syed Mohammad' 'RN ten Doeschate' 'TR Birt'
 'AG Murtaza' 'I Malhotra' 'L Ablish' 'AC Blizzard' 'CA Ingram' 'S Nadeem'
 'VR Aaron' 'JEC Franklin' 'BA Bhatt' 'Shakib Al Hasan' 'F du Plessis'
 'RE Levi' 'GJ Maxwell' 'KK Cooper' 'JP Faulkner' 'HV Patel'
 'DAJ Bracewell' 'DJ Harris' 'Ankit Sharma' 'SP Narine' 'AA Chavan'
 'GB Hogg' 'RR Bhatkal' 'CJ McKay' 'N Saini' 'DA Miller' 'Azhar Mahmood'
 'NLTC Perera' 'RJ Peterson' 'KMDN Kulasekara' 'A Ashish Reddy'
 'V Pratap Singh' 'Gurkeerat Singh' 'PA Reddy' 'P Awana' 'AD Russell'
 'P Negi' 'A Chandila' 'CA Lynn' 'P Parameswaran' 'Sunny Gupta'
 'MC Juneja' 'KK Nair' 'MDKJ Perera' 'R Shukla' 'B Laughlin' 'AS Rajpoot'
 'JD Unadkat' 'GH Vihari' 'Mohammed Shami' 'BMAJ Mendis' 'M Vohra'
 'R Rampaul' 'CH Morris' 'SV Samson' 'SMSM Senanayake' 'BJ Rohrer'
 'KL Rahul' 'R Dhawan' 'MG Johnson' 'Q de Kock' 'BB Samantray' 'CM Gautam'
 'X Thalaivan Sargunam' 'DJG Sammy' 'MM Sharma' 'Sandeep Sharma' 'S Kaul'
 'Sachin Baby' 'PV Tambe' 'NM Coulter-Nile' 'SA Yadav' 'CJ Anderson'
 'NJ Maddinson' 'AR Patel' 'JJ Bumrah' 'JDS Neesham' 'SPD Smith' 'B Kumar'
 'TG Southee' 'S Rana' 'MA Starc' 'BR Dunk' 'RR Rossouw' 'KW Richardson'
 'Shivam Sharma' 'YS Chahal' 'LMP Simmons' 'VH Zol' 'BCJ Cutting'
 'Imran Tahir' 'WD Parnell' 'BE Hendricks' 'S Gopal' 'M de Lange'
 'R Tewatia' 'JO Holder' 'Karanveer Singh' 'SS Iyer' 'DJ Hooda'
 'Anureet Singh' 'KS Williamson' 'Parvez Rasool' 'SA Abbott' 'J Suchith'
 'RG More' 'HH Pandya' 'D Wiese' 'SN Khan' 'MJ McClenaghan'
 'DJ Muthuswami' 'PJ Cummins' 'SN Thakur' 'CR Brathwaite' 'MP Stoinis'
 'Ishan Kishan' 'C Munro' 'JC Buttler' 'P Sahu' 'KH Pandya' 'AD Nath'
 'MJ Guptill' 'KJ Abbott' 'TM Head' 'NS Naik' 'RR Pant' 'SW Billings'
 'KC Cariappa' 'Swapnil Singh' 'HM Amla' 'F Behardien' 'N Rana' 'BB Sran'
 'S Kaushik' 'J Yadav' 'ER Dwivedi' 'CJ Jordan' 'TS Mills' 'A Choudhary'
 'JJ Roy' 'Vishnu Vinod' 'Basil Thampi' 'CR Woakes' 'V Shankar'
 'Rashid Khan' 'C de Grandhomme' 'Mohammad Nabi' 'AJ Tye' 'K Rabada'
 'Kuldeep Yadav' 'S Badree' 'AR Bawne' 'SP Jackson' 'Ankit Soni'
 'AF Milne' 'MN Samuels' 'TA Boult' 'E Lewis' 'DL Chahar' 'MA Wood'
 'RK Singh' 'DJM Short' 'BA Stokes' 'RA Tripathi' 'K Gowtham' 'TK Curran'
 'M Markande' 'B Stanlake' 'Mujeeb Ur Rahman' 'Washington Sundar'
 'A Dananjaya' 'Shubman Gill' 'Shivam Mavi' 'Mohammed Siraj' 'H Klaasen'
 'RK Bhui' 'JC Archer' 'PP Shaw' 'LE Plunkett' 'Mustafizur Rahman'
 'AD Hales' 'MK Lomror' 'M Ashwin' 'DR Shorey' 'MM Ali'
 'M Prasidh Krishna' 'P Chopra' 'JPR Scantlebury-Searles'
 'Abhishek Sharma' 'IS Sodhi' 'SO Hetmyer' 'S Dube' 'Navdeep Saini'
 'JM Bairstow' 'KMA Paul' 'Rasikh Salam' 'N Pooran' 'P Ray Barman'
 'SM Curran' 'GC Viljoen' 'Avesh Khan' 'S Lamichhane' 'RD Chahar'
 'HF Gurney' 'SD Lad' 'AS Joseph' 'R Parag' 'MJ Santner' 'JL Denly'
 'LS Livingstone' 'KK Ahmed' 'AJ Turner' 'Harpreet Brar' 'SE Rutherford'
 'Y Prithvi Raj' 'P Simran Singh' 'JL Pattinson' 'A Nortje' 'T Banton'
 'LH Ferguson' 'D Padikkal' 'YBK Jaiswal' 'RD Gaikwad' 'TU Deshpande'
 'Abdul Samad' 'PK Garg' 'JR Philippe' 'Kartik Tyagi' 'KL Nagarkoti'
 'CV Varun' 'I Udana' 'Ravi Bishnoi' 'Shahbaz Ahmed' 'AT Carey'
 'N Jagadeesan' 'T Natarajan' 'P Dubey' 'SS Cottrell' 'Arshdeep Singh'
 'DR Sams' 'M Jansen' 'RM Patidar' 'KA Jamieson' 'M Shahrukh Khan'
 'JA Richardson' 'Lalit Yadav' 'Virat Singh' 'FA Allen' 'C Sakariya'
 'DJ Malan' 'KS Bharat' 'PWH de Silva' 'VR Iyer' 'GD Phillips'
 'GHS Garton' 'AK Markram' 'K Yadav' 'T Shamsi' 'NT Ellis' 'RV Patel'
 'TL Seifert' 'Anmolpreet Singh' 'Anuj Rawat' 'TH David' 'DP Conway'
 'Tilak Varma' 'R Powell' 'PBB Rajapaksa' 'RA Bawa' 'OF Smith' 'A Badoni'
 'PVD Chameera' 'A Manohar' 'R Shepherd' 'DJ Willey' 'D Pretorius'
 'JM Sharma' 'VG Arora' 'Mukesh Choudhary' 'Umran Malik' 'D Brevis'
 'B Sai Sudharsan' 'Ramandeep Singh' 'HE van der Dussen' 'SS Prabhudessai'
 'Akash Deep' 'JR Hazlewood' 'KR Sen' 'Aman Hakim Khan' 'HR Shokeen'
 'Yash Dayal' 'DJ Mitchell' 'Shashank Singh' 'B Indrajith' 'Harshit Rana'
 'Mohsin Khan' 'Simarjeet Singh' 'M Theekshana' 'AS Roy'
 'Fazalhaq Farooqi' 'K Kartikeya' 'RP Meredith' 'KS Sharma' 'T Stubbs'
 'R Sanjay Yadav' 'A Tomar' 'PN Mankad' 'OC McCoy' 'Sikandar Raza'
 'Rahmanullah Gurbaz' 'KR Mayers' 'Mukesh Kumar' 'HC Brook' 'AU Rashid'
 'C Green' 'N Wadhera' 'Arshad Khan' 'Abishek Porel' 'Dhruv Jurel'
 'MG Bracewell' 'MW Short' 'Mohit Rathee' 'YV Dhull' 'A Zampa'
 'Yudhvir Singh' 'Atharva Taide' 'Harpreet Singh' 'Liton Das' 'PD Salt'
 'Vijaykumar Vyshak' 'Abdul Basith' 'Arjun Tendulkar' 'JP Behrendorff'
 'AJ Hosein' 'Naveen-ul-Haq' 'Noor Ahmad' 'JE Root' 'KM Asif' 'MD Shanaka'
 'Sanvir Singh' 'Vivrant Sharma' 'DG Nalkande' 'R Ravindra' 'SD Hope'
 'Sumit Kumar' 'Azmatullah Omarzai' 'Naman Dhir' 'G Coetzee' 'SZ Mulani'
 'Sameer Rizvi' 'SH Johnson' 'Akash Madhwal' 'SB Dubey' 'Mayank Dagar'
 'RJW Topley' 'A Raghuvanshi' 'Ashutosh Sharma' 'Nithish Kumar Reddy'
 'Saurav Chauhan' 'Kumar Kushagra' 'BR Sharath' 'WG Jacks'
 'J Fraser-McGurk' 'Tanush Kotian' 'KA Maharaj' 'Arshad Khan (2)'
 'R Sai Kishore' 'L Wood' 'LB Williams' 'AA Kulkarni' 'MJ Suthar'
 'RJ Gleeson' 'Gulbadin Naib' 'D Ferreira' 'A Kamboj' 'T Kohler-Cadmore'
 'Shivam Singh' 'V Viyaskanth' 'P Amarnath' 'B Geeves' 'Gagandeep Singh'
 'A Nel' 'AM Salvi' 'RR Bose' 'SS Sarkar' 'RA Shaikh' 'C Ganapathy'
 'MB Parmar' 'SB Wagh' 'ND Doshi' 'AA Kazi' 'Anand Rajan' 'RW Price'
 'TP Sudhindra' 'BW Hilfenhaus' 'P Suyal' 'MG Neser' 'IC Pandey'
 'K Santokie' 'JW Hastings' 'GS Sandhu' 'Tejas Baroka' 'SS Agarwal'
 'NB Singh' 'MJ Henry' 'K Khejroliya' 'L Ngidi' 'CJ Dala' 'SC Kuggeleijn'
 'S Midhun' 'O Thomas' 'S Sandeep Warrier' 'CJ Green' 'Monu Kumar'
 'LI Meriwala' 'Jalaj S Saxena' 'Akash Singh' 'IC Porel' 'PH Solanki'
 'M Pathirana' 'J Little' 'RS Hangargekar' 'NA Saini' 'Yash Thakur'
 'Suyash Sharma' 'SSB Magala' 'D Jansen' 'Gurnoor Brar' 'R Goyal'
 'H Sharma' 'N Burger' 'KT Maphaka' 'M Siddharth' 'MP Yadav' 'S Joseph'
 'N Thushara' 'V Kaverappa'"""
    

    
players = players.replace("' '", "','")
players = players.replace("\n",",")


print(players)